# finget 策略配置文件

latest_datasets:
  - daily
  - adj_factor
  - daily_basic
  - stk_factor_pro
  - report_rc
  - broker_recommend
  - stk_surv

scan_datasets:
  - daily
  - weekly
  - adj_factor
  - daily_basic
